# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'src/view/ui/option_database/option_database.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Frame(object):
    def setupUi(self, Frame):
        Frame.setObjectName("Frame")
        Frame.resize(400, 300)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(Frame)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(Frame)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.pbDeleteRecentDatabase = QtWidgets.QPushButton(Frame)
        self.pbDeleteRecentDatabase.setObjectName("pbDeleteRecentDatabase")
        self.verticalLayout.addWidget(self.pbDeleteRecentDatabase)
        self.lMessageOptionDatabase = QtWidgets.QLabel(Frame)
        self.lMessageOptionDatabase.setText("")
        self.lMessageOptionDatabase.setAlignment(QtCore.Qt.AlignCenter)
        self.lMessageOptionDatabase.setObjectName("lMessageOptionDatabase")
        self.verticalLayout.addWidget(self.lMessageOptionDatabase)
        self.label_2 = QtWidgets.QLabel(Frame)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.lvListDatabases = QtWidgets.QListView(Frame)
        self.lvListDatabases.setObjectName("lvListDatabases")
        self.verticalLayout.addWidget(self.lvListDatabases)
        self.line = QtWidgets.QFrame(Frame)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.verticalLayout_3.addLayout(self.verticalLayout)

        self.retranslateUi(Frame)
        QtCore.QMetaObject.connectSlotsByName(Frame)

    def retranslateUi(self, Frame):
        _translate = QtCore.QCoreApplication.translate
        Frame.setWindowTitle(_translate("Frame", "Frame"))
        self.label.setText(_translate("Frame", "Welcome to ProgrammingDirectories"))
        self.pbDeleteRecentDatabase.setText(_translate("Frame", "Delete recent database"))
        self.label_2.setText(_translate("Frame", "Recent database"))
